name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide clear steps so we can reproduce it quickly.
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues and didn't find a duplicate.
          required: true
        - label: I can reproduce this on the latest code from `main`.
          required: false
  - type: textarea
    id: summary
    attributes:
      label: Bug summary
      description: What happened?
      placeholder: "Example: While trying `mt-dlp` on..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Add exact steps.
      placeholder: |
        If the bug report is a file downloading error (being unable to download from some link), fill this with "Not Applicable or N/A". If however, this          is a problem in the downloader itself (such as threads not being created), fill this in.
      validations:
        required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "Threads must be created because..."
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "Downloader works in..."
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS details, CPU architecture
      placeholder: "Fedora Linux, x64"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Extra context
      description: Screenshots, console errors, or videos.
      render: shell
