name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.h'
      - '**.c'
      - '**.cc'
      - '**.hpp'
      - '**.cpp'
      - '**.cxx'
      - '**/CMakeLists.txt'
      - '**.cmake'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.h'
      - '**.c'
      - '**.cc'
      - '**.hpp'
      - '**.cpp'
      - '**.cxx'
      - '**/CMakeLists.txt'
      - '**.cmake'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev ninja-build

    - name: Cache FTXUI
      id: cache-ftxui
      uses: actions/cache@v4
      with:
        path: ./ftxui-dist
        key: ${{ runner.os }}-ftxui-v1

    - name: Build and Install FTXUI
      if: steps.cache-ftxui.outputs.cache-hit != 'true'
      run: |
        git clone --depth 1 https://github.com/ArthurSonzogni/FTXUI.git
        cd FTXUI
        cmake -B build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/ftxui-dist -DFTXUI_BUILD_EXAMPLES=OFF -DFTXUI_BUILD_DOCS=OFF
        cmake --build build --target install

    - name: Configure with Preset
      run: |
        cmake --preset linux-release -DCMAKE_PREFIX_PATH=${{ github.workspace }}/ftxui-dist

    - name: Build with Preset
      run: cmake --build --preset linux-release
